name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.6.3
  - seaborn=0.12.2
  - pandas=1.5.3
  - pip=23.0
  - ydata-profiling=4.1.2
  - pyarrow=9.0.0
  - pip:
      - wandb==0.13.10