name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.2.2
  - ipython=8.11.0
  - notebook=6.5.3
  - jupyterlab=3.6.3
  - cookiecutter=2.1.1
  - hydra-core=1.3.2
  - matplotlib=3.6.3
  - pandas=1.5.3
  - git=2.33.0
  - pip=23.0
  - pip:
      - wandb==0.13.10
