name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=23.0
  - mlflow=2.2.2
  - scikit-learn=1.2.2
  - matplotlib=3.6.3
  - pillow=9.4.0
  - pip:
      - wandb==0.13.10