name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.28.2
  - pip=23.0
  - mlflow=2.2.2
  - pip:
      - wandb==0.13.10
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
